project:
  type: website

website:
  title: "Armand Bashige's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com
      - icon: github
        href: https://github.com/Bashigea
      - icon: github
        href: https://github.com/Bashgea
format:
  html:
    theme: darkly
    css: styles.css



