---
title: "Day 15 - Homework Responses"
author: "YOUR NAME HERE"
format: gfm
---

## Preliminaries
Link to google doc for instructions: [LINK](https://docs.google.com/document/d/1pn4HjL9HpNtZh2Rtc1usbTJs7bjlQ68WIvYF1qYvKms/edit?usp=sharing)


<div style="background-color: #f0f8ff; border-left: 5px solid #007acc; padding: 10px;">
## (20 points) Code of Ethics
I'm interested in understanding your process for completing all the questions in this assignment. Please tell me about the tools and resources—including any use of AI—that helped you with your work. Please remember to follow the outlined [Code of Ethics](https://docs.google.com/document/d/1lMvzPTGUAaMnH0KPibShQ1ualuo8uqICCexkh8zmsW8/edit?usp=sharing).  Because our understanding of how to work with AI tools is emerging, please err on the side of including too much detail rather than too little.


TYPE YOUR RESPONSE HERE

</div>


## Problem 1 (20 points)
Discuss with your Hennepin County group: where can you imagine yourself using logistic regression in your project? Sketch out some possible ideas that you can incorporate the tidymodels workflow into binary classification.  (I encourage you to try to incorporate test your ideas as well!)

TYPE YOUR RESPONSE HERE

## Problem 2 (20 points)
Review [Chapter 18 in Modern Data Science with R](https://www.tidymodels.org/start/). I encourage you to evaluate each of these expressions on your computer.  I imagine there are a lot of terms and ideas that are familiar to you, and perhaps some that are unfamiliar to you.  Make a listing of concepts you:

  a. understood
  b. didn’t understand initially, but working through the examples led to more understanding
  c. still unfamiliar to you, even after working through the articles.


TYPE RESPONSE BELOW

## Problem 3 (10 points)
In class we worked through two different models (“null” and “plus”) to predict whether or not a locality had an unemployment above 6%. Using the variables in joined_dataset, set up a third logistic regression example using different predictor variables (or combinations of them).  Some starter code is below:


```{r}
#| echo: false
#| message: false

library(tidyverse)
library(tidymodels)
tidymodels_prefer()   ### Set any conflicts to prefer tidymodels

### Load in the data
data_file <- here::here("day15","data","employment_education.Rda")
load(data_file)


### Set the unemployment threshold for the model
unemployment_thresh <- 6  

### Create a new indicator variable for logistic regression
unemployment_education_data_new <- unemployment_education_data |>
  mutate(above_indicator = (unemployment_rate > unemployment_thresh),
         above_indicator = as.factor(above_indicator)) |>  # Set as a factor for regression
  na.omit()

# YOU NEED TO FILL IN FROM THE REMAINING R FILE WORKED ON IN CLASS


```


  a. Explain why you chose the combinations of variables you want to do.
  
  TYPE YOUR RESPONSE HERE
  
  b. After the logistic regression, evaluate the effect these new covariates have on the accuracy and predictive power of your model on both the training and the testing data.

  TYPE YOUR RESPONSE HERE
  
  
  
**When finished, don’t forget to render your file, commit and push to your repo, and then submit an issue on github, tagging me saying that it is ready for grading.**